require_relative '../response'

# The first stage of the FSD login process.
# Prefixed with $ID, this line contains the users callsign, client ID and string, CID, and another UUID generated by the client.

class RequestLoginIdent

  def initialize(line, user_data, connected_users, logger)
    @line = line
    @user_data = user_data
    @connected_users = connected_users
    @logger = logger
  end

  def process
    splline = @line.split(':')

    callsign = splline[0].split('$ID')[1]

    if @connected_users.keys.include? callsign
      response = Response.new
      response.kill_connection
      response.push "$ERserver:unknown:001::The callsign #{callsign} is already in use"
      return response
    end

    # Do not assign @user_data[:callsign] before we
    # check for duplicate callsigns to
    # avoid a bug where the already connected user
    # with the callsign being disconnected

    @user_data[:callsign] = callsign
    @user_data[:client_id] = splline[2]
    @user_data[:client_string] = splline[3]
    @user_data[:cid] = splline[6]
    @user_data[:client_uuid] = splline[8]
    @logger.info "New callsign: #{@user_data[:callsign]}"
    @user_data[:id_complete?] = true
    Response.empty
  end

end